from typing import Protocol

from models.entity import Entity
from models.relation import Relation
from models.statement import Statement, StatementStatus


class GraphStore(Protocol):
    """Abstract interface for graph persistence."""

    def add_entity(self, entity: Entity) -> Entity: ...

    def get_entity(self, entity_id: str) -> Entity | None: ...

    def update_entity(self, entity: Entity) -> Entity: ...

    def add_relation(self, relation: Relation) -> Relation: ...

    def get_relation(self, relation_id: str) -> Relation | None: ...

    def add_statement(self, statement: Statement) -> Statement: ...

    def get_statement(self, statement_id: str) -> Statement | None: ...

    def update_statement(self, statement: Statement) -> Statement: ...

    def statements_for_subject(
        self, subject_id: str, *, status: StatementStatus | None = StatementStatus.ACTIVE
    ) -> list[Statement]: ...

    def statements_for_object(
        self, object_id: str, *, status: StatementStatus | None = StatementStatus.ACTIVE
    ) -> list[Statement]: ...

    def statements_by_relation(
        self, relation_id: str, *, status: StatementStatus | None = StatementStatus.ACTIVE
    ) -> list[Statement]: ...

    def all_entities(self) -> list[Entity]: ...

    def all_relations(self) -> list[Relation]: ...

    def all_statements(self, *, status: StatementStatus | None = None) -> list[Statement]: ...
